apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-service
spec:
  selector:
    matchLabels:
      app: deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: deploy
    spec:
      containers:
        - name: deploy-container
          image: my-registry/deploy-service:v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: deploy-secret
                  key: DB_DSN
          envFrom:
            - configMapRef:
                name: deploy-configmap
      restartPolicy: Always
