apiVersion: v1
kind: Service
metadata:
  name: deploy-service
spec:
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
      name: http
    - port: 50051
      targetPort: 9083
      name: grpc
  selector:
    app: deploy
