{{- range $name, $svc := .Values.services }}
{{- if or $svc.dbDsn $svc.needsJwt (eq $name "auth-service") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-secret
  labels:
    app: {{ $svc.app }}
type: Opaque
data:
  {{- if $svc.dbDsn }}
  DB_DSN: {{ $svc.dbDsn | b64enc | quote }}
  {{- end }}
  {{- if or $svc.needsJwt (eq $name "auth-service") }}
  JWT_SECRET: {{ $.Values.global.jwtSecret | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
