apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: my-registry/auth-service:v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: DB_DSN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
          envFrom:
            - configMapRef:
                name: auth-configmap
      restartPolicy: Always