apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
    - port: 50051
      targetPort: 9081
      name: grpc
  selector:
    app: auth
